### ISSUE TITLE
Conversion script - Simple likes -> Thank you/like system

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#44]
Here is a conversion script for migrating from Thank you/like system into Simple Like system. Can we revert this easily?

https://github.com/euantor/SimpleLikes/archive/current.zip

**Comment by Cu8eR** [comment]
@WhiteNeo - so converter for Thanks SaeedGh & ThankYou MyBB System Converter are complete. Amazing job, really huge thanks man! Last thing is the converter for SimpleLike system.

**Comment by WhiteNeo** [comment]
Yes but i didnot tested yet, because Simple Likes only use user id and post id, TYL uses date and poster uid so i have to see how can this data can be filled by itself, maybe latest user activity or i dunno, really, user activity was aa good point to fill data but i have to test it.

Aanyway you can use it without data lose, so any ideas can be apreciated.

**Comment by Cu8eR** [comment]
Registered time or last time online would be the best method

**Comment by WhiteNeo** [comment]
Yes i think so, but i have to get some db with that plugin in use to see how it works, anyway all data was been taken i think but without data and that facts, but i have to get some db with this mod enabled and working on to see how it works and how can we do to trnslate and add values :D. Anyway if i don't find it maybe can work in it in a few months when i have more time, because right now i have to work all week, and have no time to nothing :(

**Comment by WhiteNeo** [comment]
I think this can be closed due a missing data to test it but should to work fine only missind date but haave to work...

**Comment by Cu8eR** [comment]
So it should be working, right? I cannot test it, no forum with simple likes unfortunately :( Anyway thank you!
