### ISSUE TITLE
Minify JS

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#45]
No big deal but it could bring faster loading speeds of websites. I would like to see a setting for this: use minified version of JS? Yes/No

**Comment by Cu8eR** [comment]
@WhiteNeo - What do you think? Is it necessary? We can use only minified version (no switch on/off for normal or minified version).

**Comment by WhiteNeo** [comment]
Ok i've set values by defaault but minified is maybe usefull, but i dunno, well today i fix it because i have to go out some days and i dunno where i have to go and when i came back, so i add some code to my repo, but as ever have to test to set a new version.

Deactivate old version, upload new files, because i add some lang vars and have to use it with jGrowl to make more visible, then upload new files and Activate again. To make all changes and that's all, i set to default he value by AJAX, but maybe i take it out to set only collapsable or expandable at the first time and the do nothing xD, well it's more easy delete than create, so i let in this way until i come back.

**Comment by Cu8eR** [comment]
@WhiteNeo - I checked your latest changes - they look good. Just 2 things:
1) I like the popup notification in the right top corner when you add/remove thanks/like to post, but not everybody has same feelingand needs - so it would be better if we have a setting for this in ACP (Show notification - on/off). 

2) About minified JS version - same as above, add switch - use minified JS version - on/off

**Comment by WhiteNeo** [comment]
As i said before is jgrowl ajax notification to know something is happening like javascript notifications. All MyBB core uses so you can disable it on admincp deleting the ajax requests.

**Comment by WhiteNeo** [comment]
Note: is only test version the final version was the final code mod and may change. Sometimes server is bussy and users send again and again likes because they dont know this. With this notification user knows is sending and stay alert i use this and trust me many errors have reduced about this fact.

Is necesary and commented on the official post request by users. But this can be removed and is not the final code because i will work on it and make it work fine on all senses when i got time to do.

**Comment by Cu8eR** [comment]
No, I would like to keep this notification, they are great.

Just TODO list:
- use same style like MyBB fot these notification 
- swithc on/off in plugin - is it possible, or not?

Everything else should be OK, do you have any other ideas?

**Comment by Cu8eR** [comment]
@WhiteNeo - I think that minify JS is not required in our case - it would save only 1kB and it would bring more problems than cons

**Comment by adsol93** [comment]
Hey there, may I offer something? 

Why don't you add the option of notifying the user with a PM when someone has liked his/her post?

**Comment by Cu8eR** [comment]
It is not possible in MyBB 1.8 - this is only Thank you/like system, not MyAlerts plugin - contact devs of this plugin here: https://github.com/MyBBStuff/MyAlerts

**Comment by adsol93** [comment]
I know, I just thought that maybe it was possible with PMs because MyAlerts works different.

**Comment by Cu8eR** [comment]
No, it wont work... it is not possible without huge core modifications. It wont happen, srry
