### ISSUE TITLE
PHP error on plugin activation

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#50]
@WhiteNeo - with latest mod version (GitHub release) there is a problem during activation

![124 apr 15](https://cloud.githubusercontent.com/assets/778890/7160842/df6c5158-e38b-11e4-8286-25b3df1af4f2.jpg)

**Comment by Cu8eR** [comment]
@WhiteNeo - we need to add a notification that myalerts is not installed od skip this if there is no myalerts

**Comment by WhiteNeo** [comment]
Theres an error of host paths, nothing to be with MyAlerts, all functions are fine and if no MyAlerts have to do nothing that error is because don't find the plugin file called thankyoulike or name is changed or something like that, but this caan be fixed. We need more detaailed info about that error.

Server side version. ?
Engine used on your db ?
php version ?
is absolute or won't your forum path ?
etc...

Because by default have to work with or without MyAlerts i'm make sure of that before make all entire code, problem is inside your own plugin file of thanyoulike not founded :D.

**Comment by Cu8eR** [comment]
@WhiteNeo - user reported me that this error is hown only for a few seconds after activation.. after that everything works fine. It happens only with version from GitHub (with MyAlerts integration), not with last "stable" version downloaded from MyBB mod site. I will try it

**Comment by Cu8eR** [comment]
@WhiteNeo - I just saw that you added a fix for this (at least line 395). So is it fixed? I cannot reproduce any error on my side

**Comment by WhiteNeo** [comment]
Yes as i say its a calling of a file inside himself but called from another path i can change path but is unnecesary. This line only have to been added on root file for coding reduce purposes but i create quickly the code on this release because i have downloaded from mybb.

So i only add code but i tell for that reason have to test it.

I did not test it because i dont have time to do yet.

I close this and maybe next week i review because on my test forum i have to make some changes on code because some plugin options wont work on mybb latest release. I have to check this to see if all goes fine opt by opt.

Maybe if i finish some few things i can review it to release the 1.9.2 stable version.

See yah !!!

**Comment by Cu8eR** [comment]
@WhiteNeo - ok, now I can say only one thing - alerts for thankyoulike is not registered in myalerts after activate and installation
