### ISSUE TITLE
Add a time interval before another adding/removing 

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#60]
Add a secure interval which could block fast adding/removing thanks/like to the post.

For example 10-15 seconds

**Comment by Cu8eR** [comment]
@WhiteNeo - hi, is it possible to add this? I just checked code and I am not sure how to add it easily. Do you have any ideas? 

Same system like in MyBB - wait XX seconds for posting another thread/post - it could be hardcoded (for example 15 seconds)

**Comment by WhiteNeo** [comment]
I see this before but i don't think can be added easily, because i maade on my thanks system something like that, but in this case onli when you add some thank then register time and have to wait to do something else, remove or add, but if you delete then nothing be done, because in db all data was deleted in this cases and there's no new time to be compared with.

That reason can make a fact and would be a posible taken by users like very buggy or something, maybe with cache on events can be done, i dunno. I think a cookie can be used, but if delete cookies then again an error can be taken, so i haaave no ideas on how to really in my thanks system i do it as i said and works fine, but haave to be bether :D

**Comment by Cu8eR** [comment]
@WhiteNeo - OK, I see the problem. I close this. Thx anyway!
