### ISSUE TITLE
Alerts are not shown after last update (1.9.3)

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#64]
@WhiteNeo

**Comment by WhiteNeo** [comment]
That is because i have to made changes on my localhost, then on my repo and then when all goes fine i have to add here and that reason takes much time for me and i haave no time to review it again, and again and again even if i don't use this and never will use it. So i have to review again files to found AGAIN the error and fix it, beccause as i said before is only TEST version UNTIL all goes fine then RELEASE IT not before for things like this, because i have many files on my pc an i dunno wheres the right and wrong files and working on files, jajaaja. Sorry about that but for that reason i never say is stable until i have time to test and then when all goes fine saay ooh now is stable common release it :D and well i have no idea where aare my files because i deleted my repo because i have to work here when i have time, righ now i fix alerts typo because ii forgot to change some parts of code in this repo, about another issues i have to download, test and then as i say put as stable, then release it....

**Comment by WhiteNeo** [comment]
Ok testing and reviewing last details to release it !!! I think right now is stable with the latest commits i made but i have to be shure of all goes fine, maaaybe some help o test be usefull right now :D, anyway i continue with this review and last details, thanks...

**Comment by Cu8eR** [comment]
@WhiteNeo - awesome, I will test it in the morning (in 10 hours)

**Comment by Cu8eR** [comment]
Fixed - https://github.com/Cu8eR/thankyou-like-plugin/commit/8646414114683247f766cca77671ec8b59b9f487
