### ISSUE TITLE
Really long delay with new v1.9.3 version until thanks/like is added

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#65]
@WhiteNeo 

I just test it locally and I think there must be a problem with latest changes in JS file

**Comment by Cu8eR** [comment]
@WhiteNeo - OK, I have found issue - every disable/enable of plugin adds another <script></script> stuff into show thread template. It is loaded multiple times, thats the issue. Could you check this? I think there must be somwthing wrong with activate/deactivate function in plugin.

**Comment by WhiteNeo** [comment]
Ok thank you eldenroot i´ve review this last version from github to know what is happen aand fix all bugs this weekend at least to leave a stable and now you can release it and use it on live forums after i review it, thanks for your patience.

Cheers :D

**Comment by Cu8eR** [comment]
@WhiteNeo - I tested it locally, it works fine. Also 3 users reported on mybb forum that this beta version is much better than the last one - alerts are registered and shown. I need to test performance issue and installation/uninstallation process

**Comment by WhiteNeo** [comment]
Have to works all fine i tested since yesterday so it's green lights to use it and i made a converter, but this last haave to bee tested !!

I Simple Likes there are missing data because only exist two to be taken, miss date and post uid, but maybe with recount fix this i dunno, i have to get a Simple Likes db to test with, but with my system and thanks SaedGh and others works fine. But have to test, i upload it !!!

All data was stored so no lose of data if something goes wrong you can re use old thanks system or another one.

**Comment by Cu8eR** [comment]
@WhiteNeo - Yeah, I tried to release a converter from SimpleLikes plugin with reverse engineering but without success. I am just a begineer with this kind of scripts. Anyway I will close this issue, it looks fine on my testing board.
