### ISSUE TITLE
Register alerts type to myalerts without uninstall of plugin

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#72]
Add option to plugin tab to enable (reenable) alerts for myalerts

(register thankyoulike alerts to myalerts without uninstall/install process)

This is doable in DVZ mentions for example

**Comment by WhiteNeo** [comment]
That can be done with a conditional and a new function running but not sure at all, anyway i try to set this on this and mine plugin too, and i've add some code changes on my repo so maybe some changes cann be added in a few days. If i have the time then i do it asap.

**Comment by WhiteNeo** [comment]
Added, missing test to see if it works fine to close this enhacement....

**Comment by Cu8eR** [comment]
Good job, I am not at home this week, but I will test it soon.

@WhiteNeo - is there anything else what you have to do on your list for another build?

**Comment by Cu8eR** [comment]
@WhiteNeo - I have added some changes for this commit. Everything is fine, BUT we need to add a button to run a registration of new alert type into MyAlerts plugin without Deactivation/Uninstall of TYL System

**Comment by WhiteNeo** [comment]
There's a link to do that, click on link and integration have to work. You can style as a button or anything you like, but personally i did not like buttons in admin cp, on all my mods i use links to configure options and moreover.

If another mod have this i dunno, but i never see another mods to make new ones, i prefer to do my own code and in the way i think have to work, but right now it's a very easy task to chaneg url with orange color (link to do the same task if you use a button, and that is a job of 1 or 2 minutes to do). The first thing here it's test if this works fine on all hosts, because i test on some hosts of users who use this mod or my mod and both of them use the same function to do that, so i think have to work. Only change text part for an input and it's done, it's a very easy task to do.

**Comment by Cu8eR** [comment]
I see messages about MyAlerts integration but I cannot click on the link to register a new alert type... Is it clickable? Because I cannot click on it, at least not as you wrote above. Can you check it/add this? Thank you

**Comment by WhiteNeo** [comment]
ah yes i review this then thanks for this report.

I think it's a link appeared when MyAlerts are not in the list, otherwise you can see on red or green. But only if MyAlerts is there.

Thanks i check this asap.

**Comment by WhiteNeo** [comment]
Fixed, need some tests too to close issue!!

**Comment by Cu8eR** [comment]
Ok, I will. Thx

**Comment by WhiteNeo** [comment]
Take your time i am testing right now all seems to be fine, but need more tests yet to know if works fine :dancers:

**Comment by Cu8eR** [comment]
Tested, works fine! THX!
