### ISSUE TITLE
Database query error when looking up thanked posts

### ISSUE THREAD

**Issue by aaaaaa123456789** [Cu8eR/thankyou-like-plugin#74]
When looking up your own thanked posts, if the website has any forums in which you can only see your own posts, there are a few database query errors, at least on MySQL.
(Using version 1.9.6 of the plugin)

I fixed the errors myself, there were caused by a missing JOIN, but I'm not sure if that would break anything else. Here's my fixed version of tylsearch.php: http://forums.acidch.at/files/tylsearch.tgz

**Comment by Cu8eR** [comment]
@WhiteNeo - what do you think?

**Comment by WhiteNeo** [comment]
I really don't know because never tested that parts, but i review this weekend to get some code changes on the mod if necesary.

In the case this error is on the latest repo we have to maake sure wich parts of code have changed or where is the error to review because sometimes users do code changes wothout the knowledge to do it and sometimes this changes produces more errors than fix an error.

**Comment by aaaaaa123456789** [comment]
I just fixed the incorrect queries, to be honest. Everything *should* work
just fine...
Also, you can visit my forums (forums.acidch.at) if you want to see it live.

**Comment by WhiteNeo** [comment]
To be honest we have to review it because don't have an inquerie reported about this error you're talking about, because many users have it on their forums, we really apreciate it but have to review to maake correct queries and not release aa version with some baad code, becaue this mod was taken from 1.6.x series and never had an error similar like mentioned by you.

So maaybe some parts of code haae to rewrite due the core mods of 1.8.x series but haave to o in the right way, not only the commented by you because we have to make sure the code was in te right way and the file you send not tell nothing i recommend in the future to make an issues report and we verify and we fix it asap but in the right direction to do things.

**Comment by Cu8eR** [comment]
@aaaaaa123456789 - could you tell me which error was it? is it something similar to this?
https://github.com/Cu8eR/thankyou-like-plugin/issues/82

**Comment by aaaaaa123456789** [comment]
It wasn't the same error. The error that I had showed up because the query was referencing two tables, but the FROM clause only had one of them (I simply fixed it by adding the other table and adding table names to the columns).

I don't have a copy of the error, but this is the thread they made in my forum about it: http://forums.acidch.at/showthread.php?tid=152

(If it matters, in my forum, table names in the database are not prefixed at all, since I have a database dedicated to the forum)

**Comment by Cu8eR** [comment]
OK, thx. Closing!
