### ISSUE TITLE
New settings: Remove the format for author´s username

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#76]
In one of the last version the format username feature was added for author of the post. We should also add a new setting for this with enable/disable this. Now this setting is missing (we can only enable/disable username format in list under the post, not above for authors username). It would be great to have it, many users complain about it :(

![t4zwpiz](https://cloud.githubusercontent.com/assets/778890/9683753/4c645160-5313-11e5-8999-c6a47b1f8940.png)

Link:
http://community.mybb.com/thread-169382-post-1171373.html#pid1171373

**Comment by WhiteNeo** [comment]
Yes i take on mind that, but i forgot to add it at the end, because i say test it this and don't released yet due this things, but nobody test it and this was released without the necesary tests to release it. For that reason i never release a version of mine plugins even if i made some changes until i'm sure of the final job :D. ANd i don't test this plugin due i have not installed and no idea on how it works, so when i make some code changes my brain only think about if that can work fine or not and make code changes, but never test it, until i have time to do and make sure if that code changes do his job :D.

I remind this to do after the release of 1.9.7.

**Comment by Cu8eR** [comment]
@WhiteNeo - v1.9.7 has a tag "BETA", so feel free to add anything. I am testing your changes everytime before I release anything. Many users on forum test this nonreleased version and send me PMs with feature requests and ideas... today I had some free time so I have added some changes into code. For now, I am done and I will be wainting for you changes

**Comment by WhiteNeo** [comment]
Ok i review it and add this when upload new code changes about the alerts too.

**Comment by WhiteNeo** [comment]
Added taken by options tyl user formatt name on list...

need to do some tests !!!

**Comment by Cu8eR** [comment]
Ok, I will check that. Users wrote me in PMs that they wanna add links and formating to users in a list under the post but disable link and formating for authors username (thats why I suggested separate option for that). What do you think?

**Comment by WhiteNeo** [comment]
I dunno, all can be done, so you can decide and tell me about this to add as new option or taken besides link, it's much easier to do in that way :D

**Comment by Cu8eR** [comment]
I understand. If you have time, please add a separate option for that. It would be better.

**Comment by WhiteNeo** [comment]
Ok let me know then how this can be added.

I think a new option for author of thanks/like formatted and link and other with only username ?

Or only link added to author and the same option as in this latest release ?

**Comment by Cu8eR** [comment]
For list of users who added thx/like for a post has an own option already - turn on/off formating (links are enabled all the time). 

For authors username of post shown above the list should have same setting like above - just:
- turn on - link and format
- turn off - no link, no format

Or do you have better idea?

**Comment by WhiteNeo** [comment]
Done, i think in this way it´s better as you said :D

**Comment by Cu8eR** [comment]
@WhiteNeo - I just arrived to home from work... I am going to test it! ;) Great work, thank you!

**Comment by Cu8eR** [comment]
Tested, works fine. I hope we wont get PMs about adding formating only for usernames in a list of users under the post :)

Anyway, I like this! I will change lang file for settings description before releasing final v1.9.7

**Comment by WhiteNeo** [comment]
It's the second idea in this post, i remove some code now, jajaaja.

https://github.com/Cu8eR/thankyou-like-plugin/issues/76#issuecomment-139476065

But maybe it's better in this way,let the users test and tell us what does they think about i think is a waste of unnecesary time to do this, in the actual way i think is the best way to show, because in other ways do the same of users wont wanted to do.

**Comment by Cu8eR** [comment]
@WhiteNeo - I agree! Leave it as it is :) Thx! Closing
