### ISSUE TITLE
Tylsearch for posts - not shown

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#81]
http://community.mybb.com/thread-169382-post-1182628.html#pid1182628

@WhiteNeo - I dont know how to reproduce it, do you have any idea? I dont understant this report fully :(

**Comment by Cu8eR** [comment]
EDIT: OK, I see the point - folder icons are not shown in tylsearch page

![bug2](https://cloud.githubusercontent.com/assets/778890/9822174/3e82ec30-58bf-11e5-8f51-319e052220f6.png)

**Comment by Cu8eR** [comment]
https://github.com/Cu8eR/thankyou-like-plugin/blob/master/tylsearch.php#L371 - this is the issue

**Comment by WhiteNeo** [comment]
Ok y see the point i rview for many time and did not findnothing unusual, but now i see the point i review it asap.

Thanks for the code it's better to know where have to work for me :+1:

**Comment by WhiteNeo** [comment]
The problem instead on css of thread not loadig in this part and even some lang data.

Well i'm reviewing it.

**Comment by WhiteNeo** [comment]
I add some missing code now have to work, i add some few rules and loading of cache stylesheet until i found aa way to load right one, use defaault one until i have a way to load stylesheet.

**Comment by Cu8eR** [comment]
Your code looks good, it works fine - tested.

I just saw a post in a MyBB forum (TYL system thread) - with latest github version folder icons are shown but no title on mouse hover

**Comment by WhiteNeo** [comment]
Just curiosity, the user have added this on their template ?

I mean title tag or not, because by default is not added, so value was not appear if does not added, i tested and works fine, but i added values manuaally ?

Search Templates:

search_results_posts_post
and
search_results_threads_thread

At the begin of template:

<span class="thread_status {$folder}">&nbsp;</span>

This values is the original i got, but i change to:

<span class="thread_status {$folder}" title="{$folder_label}">&nbsp;</span>

And in this way the var value was taken, if not appear is due to a thaat missing value, not a bug at all is only a missing value on template.

**Comment by Cu8eR** [comment]
It works fine.. anything else to add? Are we ready to release a new version soon?

**Comment by WhiteNeo** [comment]
Nope i think this version is ready to release it. i did not found a better way to add some new things until next release, like user promotions, stylesheets and more.

What do you think ?

**Comment by Cu8eR** [comment]
@WhiteNeo - what about to add title tag into instalation process? Which was mentioned above

**Comment by Cu8eR** [comment]
FIXED!
